name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # --- YEH STEP MISSING THA (IMPORTANT) ---
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # Android builds ke liye Java 17 best hai
      # ----------------------------------------

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter pub get
      
      # Agar project purana nahi hai to '--no-sound-null-safety' hata sakte hain
      - run: flutter build apk --release --no-sound-null-safety
      
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
